import type { Metadata } from "next";
import Navigation from "@/components/navigation";
import "./globals.css";
import ReactLenis from "lenis/react";

export const metadata: Metadata = {
  title: "sarhan.studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Navigation/>
        <ReactLenis root>
          {children}
        </ReactLenis>
      </body>
    </html>
  );
}
